archetype.groupId=com.zephyr.ai
archetype.artifactId=ai-agent-starter
archetype.version=1.0
packageName=com.zephyr.ai
excludePatterns=\
.env,\
log,\
.git/**,\
.idea/**,\
*.iml,\
target/**,\
.qoder/**,\
.DS_Store,\
.codex,\
.agents,\
**/archetype.properties
